### ISSUE TITLE
How can I use ib_srp on redhat 7 with targetcli_2.1.fb34?

### ISSUE THREAD

**Issue by Damon-sh** [agrover/targetcli-fb#50]
Hi,
I have install the targetcli_2.1.fb34 on redhat 7.But I haven't see the ib_srp option when I use ls.
/> ls
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 0]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  o- iscsi ............................................................................................................ [Targets: 0]
  o- loopback ......................................................................................................... [Targets: 0]
/> 

I have already load driver target_core_iblock ,target_core_mod.
[root@DATA]# lsmod |grep ib
ib_ipoib               91629  0 
ib_ucm                 22546  0 
ib_uverbs              46783  2 ib_ucm,rdma_ucm
ib_umad                18027  0 
ib_srpt                52289  0 
ib_cm                  42689  4 rdma_cm,ib_ucm,ib_srpt,ib_ipoib
ib_sa                  33950  4 rdma_cm,ib_cm,rdma_ucm,ib_ipoib
ib_mad                 43055  4 ib_cm,ib_sa,ib_srpt,ib_umad
ib_core                87335  11 rdma_cm,ib_cm,ib_sa,iw_cm,ib_mad,ib_ucm,ib_srpt,ib_umad,ib_uverbs,rdma_ucm,ib_ipoib
ib_addr                18923  3 rdma_cm,ib_core,rdma_ucm
target_core_iblock     18177  5 
target_core_mod       299412  40 target_core_iblock,target_core_pscsi,iscsi_target_mod,ib_srpt,target_core_file

The kernel version is 3.10.0-123.el7.x86_64 .

Please help me.Thanks.

**Comment by agrover** [comment]
Hi, we are looking to see if there are any entries that match "/sys/class/infiniband/*/ports/*/gids/0" to enable configuring srpt in targetcli. Does your system have any?

**Comment by Damon-sh** [comment]
Thanks a lot! I got it.
