### ISSUE TITLE
Document whether targetcli works as an iSCSI server to a XEN Cluster.

### ISSUE THREAD

**Issue by rjt** [agrover/targetcli-fb#53]
There was not much to configure with IET to allow multiple XEN host servers to simultaneously "connect" to iSCSI shares, but targetcli on CentOS7 does not work.  I can get any one of three to connect, but not the others.  

Should this work out of the box?  Does it require a newer kernel than 3.10.0-229.4.2.el7.x86_64?

Do i need to configure "Persistent Reservations" or something else to use multi-initiator access?

**Comment by rjt** [comment]
# xe sr-create name-label=srPhone02 content-type=user device-config-target=phone02.corp.eceo.us device-config-targetIQN=iqn.2015-06.us.eceo.corp.phone02:forumbackup device-config-localIQN=iqn.2013-08.us.eceo.corp.eceoxen01:diskaccess type=lvmoiscsi shared=true 
device-config:SCSIid=36001405b922ff67a04642d7a07cdaed9

Error code: SR_BACKEND_FAILURE_47
Error parameters: , The SR is not available [opterr=The SR device is currently in use]

**Comment by rjt** [comment]
XEN does not use serial numbers like VMWare, but uses the SCSIid.

**Comment by agrover** [comment]
One way to figure this out is from the target side, but another might be on the Xen side. What exactly is it checking to determine the device is in use?

**Comment by agrover** [comment]
FWIW targetcli is the configuration tool, but the core issue here probably is in the LIO kernel target itself.

**Comment by rjt** [comment]
I assumed SR_BACKEND_FAILURE_47 came from LIO / Linux-iSCSI.org, not XEN xe command line, but http://support.citrix.com/article/CTX131215 tells me it is probably a Citrix XEN error.

i will have to investigate what XEN is checking, eventually i will have to do a packet capture. 

Have not read them all by any means, but wondering what terminology of RFCs 3720 3721 7146 determines this "sharing among multiple initiators" capability, but my best guess is "Persistent Reservations".  "Multi-initiator access" is what XEN calls it, but that term is not in any of those RFCs.  What is the name of the feature i am attempting to use?

i noticed https://groups.google.com/forum/#!forum/linux-iscsi-target-users has not been used in years, so do those devs really appreciate user level questions?  Need to find an IRC channel.

**Comment by agrover** [comment]
PRs are a way to coordinate and exclude devices other than the desired ones from accessing the shared luns, but I believe that in the absence of using them, the target should not limit access to a single initiator (but people usually don't because this is a recipe for disaster unless coordination is happening via some other method.) 

The googlegroups target list is defunct since the target-devel list was established. User level questions are fine.

**Comment by rjt** [comment]
Thanks Andy.

**Comment by rjt** [comment]
i managed to get multiple Citrix XEN hosts to work just fine initiating a connection to targetcli,  but not sure yet if it was using parted or fdisk to mark it as an LVM volume.  Or was it something else such as  skipping pvcreate as my first experiments were with file, not block targets.  Please close.

**Comment by sammcj** [comment]
Sorry to comment on a closed issue but is there any reason TargetCLI creates LUNs with APTPL set to disabled rather than enabled?

There is seem to be no way to enable this manually after TargetCLI has created them so you can never persist the SCSIID metadata between hosts:

```bash
# cat /sys/kernel/config/target/core/iblock_0/iscsi_lun_r0/pr/res_*
APTPL Bit Status: Disabled
Ready to process PR APTPL metadata..
No SPC-3 Reservation holder
No SPC-3 Reservation holder
0x00000000
No SPC-3 Reservation holder
SPC-3 PR Registrations:
None
No SPC-3 Reservation holder
SPC3_PERSISTENT_RESERVATIONS
```

**Comment by agrover** [comment]
Hmm I see! I'll get on it. Please open a fresh bug and we'll use that for further discussion?

**Comment by sammcj** [comment]
thanks @agrover #56

**Comment by sammcj** [comment]
FYI I just wrote an article after working out how to persist the SCSI ID for Xen with LIO: https://smcleod.net/iscsi-scsiid-persistence/

**Comment by agrover** [comment]
thanks for the link!

**Comment by thirdwheel** [comment]
> FYI I just wrote an article after working out how to persist the SCSI ID for Xen with LIO: [REDACTED]

This has moved, new link: https://smcleod.net/tech/2015/12/14/iscsi-scsiid-persistence/

**Comment by sammcj** [comment]
Ah yes, sorry I broke that backlink!
