### ISSUE TITLE
Can't map rbd by symlink

### ISSUE THREAD

**Issue by Nefelim4ag** [agrover/targetcli-fb#57]
Hi,
i've try to use LIO for exporting RBD by iSCSI
`/dev/rbd?` is not persistent, but symlink
`/deb/rbd/<pool>/<name>` persistent
if i try to add fileio backend by symlink, targetcli just fallback to /dev/rbd? path

Can i fix it?

It's a problem, if i want to export several images from 1 iSCSI target

**Comment by agrover** [comment]
I don't quite understand.

Right now, I think targetcli is resolving symlinks to the real path, and using the real, persistent path. Is that what you're seeing, and you don't want it to do that, or is that not what you're seeing and you want me to fix it?

Can you describe how this prevents you from exporting several images from 1 iscsi target?

Thanks!

**Comment by Nefelim4ag** [comment]
Sorry for my bad english anyway.

Your understanding are right,
targetcli-fb resolve symlink and use /dev/rbd? path, instead of /dev/rbd/.../...
Devil hiding in details
When using RBD with auto map, i can't guarantee what after reboot, all devices will be in the same place:
i.e. this is a normal thing if i do:
`rbd map test_image; rbd map test_image; rbd map test_image;`
And after see 3 same devices
`/dev/rbd0; /dev/rbd1; /dev/rbd2`

Same if i use several images, i can map and unmap images dynamically
And then i create a config for exporting image:
`/dev/rbd1`
But after reboot i can get
`/dev/rbd0`

In one image setup this is not a big problem.
But with several images, what exported to several hosts, i don't expect something good, if images will swapped

I don't think what is a targetcli-fb issue, but targetcli just use symlink, as i've tested
I just ask:
Can i do something in targetcli-fb to prevent this behavior?

Thanks, anyway

**Comment by agrover** [comment]
Thanks for your explanation! I understand better now.

The change is actually over in rtslib-fb, but I think it solves the problem.

**Comment by Nefelim4ag** [comment]
@agrover,
Thanks, low bow for your work

**Comment by Nefelim4ag** [comment]
Hi, i use your latest targetcli-fb 2.1.fb42
Now it's working with symlinks thank you.

But in targetcli size of disk equal 0 bytes
I think it's because targetcli just try get symlink file size, instead of size of block device under symlink

Thanks

**Comment by agrover** [comment]
please try adding `path = os.path.realpath(str(path))` as the first line in utils.c get_size_for_blk_dev (around line 120) does that fix it? If not then please yes open a new issue because I need to spend more time looking into it. Thanks!

**Comment by Nefelim4ag** [comment]
@agrover, thanks it's help me

**Comment by agrover** [comment]
Pushed that fix to rtslib-fb. Thanks again :+1:

**Comment by Nefelim4ag** [comment]
Hi, this i again =)
New minor problem, if i want create backstore fileio by symlink, targetcli ask me for size
As i think what targetcli can first try to resolve link and get size, if possible

workaround for me now is:
Add device and after fix path in config

**Comment by agrover** [comment]
if I have `disk.img` that is 100MB and `link.link` symbolic link that points to disk.img, then if I do:

`backstores/fileio/ create disk1 link.link`

then that is working for me with no error, targetcli knows the storage object is 100MB. Can you describe in more detail the steps you're taking? Thanks.

**Comment by Nefelim4ag** [comment]
@agrover, You right, sorry, i can't reproduce it, thanks
