### ISSUE TITLE
Don't collect random while first start

### ISSUE THREAD

**Issue by Nefelim4ag** [agrover/targetcli-fb#58]
Hi,
i use targetcli-fb on virtual machine for proxy Ceph RBD disk

(i've try use heveged, but it's won't help me)

As i see targetctl take 1m+ for initializing, and as strace show, it's because targetctl try get random data while initialization

May be this process can be offloaded from first start?

/*
As i think random data used for generating UUID and other random stuff for creating new target/LUN
May be it's can be performed in targetcti?
*/

Feel free to kick me, if i miss something.

**Comment by agrover** [comment]
I agree with your analysis. We use symlinks with random names to link LUNs to storage objects, and to link MappedLUNs to LUNs.

(BTW this code is in rtslib, not targetcli)

Right now we regenerate the symlink names (the code calls these "aliases") each time we create the LUN or MappedLUN using uuid. I think we can avoid having to generate them each boot by saving alias values to saveconfig.json.

**Comment by Nefelim4ag** [comment]
@agrover , Thanks, you are the best =)
